import { createRequire } from 'module';
const require = createRequire('/opt/node22/lib/node_modules/');
const { chromium } = require('playwright');
import fs from 'fs';
const b = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const p = await b.newPage({ viewport: { width: 1400, height: 1000 } });
p.on('console', (m) => console.log('[c]', m.text())); p.on('pageerror', (e) => console.log('[err]', e.message));
await p.goto('http://localhost:5199/cards/render.html?d=' + process.argv[2] + '&r=' + process.argv[3]);
await p.waitForFunction(() => window.__img, null, { timeout: 120000 });
const url = await p.evaluate(() => window.__img);
fs.writeFileSync('/home/user/dino-rider/cards/hero-' + process.argv[2] + '.png', Buffer.from(url.split(',')[1], 'base64'));
await b.close();
